// Catálogo informado para Conformidade > Preenchimento. A ordem é intencional.
export const ceptDisciplines = [
  ['ARQ', 'Projeto de Arquitetura'],
  ['URB', 'Projeto Urbanismo'],
  ['LAY', 'Projeto de Layout'],
  ['LUM', 'Projeto Luminotécnico'],
  ['ACES', 'Projeto de Acessibilidade'],
  ['APS', 'Projeto de Paisagismo'],
  ['TSD', 'Laudo de Sondagem'],
  ['EST', 'Estrutura mista'],
  ['SCO', 'Projeto de Estruturas Concreto'],
  ['SMAD', 'Estrutura de Madeira'],
  ['CONT', 'Projeto de Contenção'],
  ['SMT', 'Projeto de Estruturas Metálicas'],
  ['FUND', 'Projeto de Fundações'],
  ['HIDS', 'Projeto de Hidrossanitário (Água Potável e Esgoto Sanitário)'],
  ['HIDA', 'Projeto Hidráulico'],
  ['ESG', 'Projeto de Esgoto'],
  ['DREN', 'Projeto de Drenagem'],
  ['GAS', 'Projeto de Gás (GLP/GN)'],
  ['REUS', 'Projeto de Reuso'],
  ['SUB', 'Projeto de Subestação'],
  ['ELET', 'Projeto de Elétrica'],
  ['SPDA', 'Projeto de SPDA (Proteção contra Descargas Atmosféricas)'],
  ['EREN', 'Projeto de Energia Renovável'],
  ['CFTV', 'Projeto de Projeto de CFTV'],
  ['SOM', 'Projeto de Sonorização ambiente'],
  ['AUVI', 'Projeto de Audio e vídeo'],
  ['ACUS', 'Projeto de Acústica'],
  ['CENO', 'Projeto de Cenotécnica'],
  ['DADO', 'Projeto de Dados'],
  ['AUTO', 'Projeto de Automação'],
  ['TELE', 'Projeto de Telecom'],
  ['AVAC', 'Projeto de AVAC (Aquecimento, Ventilação e Ar Condicionado)'],
  ['ARCO', 'Projeto de Ar Comprimido'],
  ['IMPE', 'Projeto de Impermeabilização'],
  ['ALA', 'Projeto de Alarme'],
  ['PCI', 'Projeto de PCI (Prevenção e Combate a Incêndio)'],
  ['HIDL', 'Projeto Hidrológico'],
  ['TERR', 'Projeto de Terraplanagem'],
  ['TOPO', 'Projeto Topográfico'],
  ['VPAV', 'Projeto de Vias e Pavimentação'],
  ['SINS', 'Projeto de Sinalização e Segurança Viária'],
  ['MEC', 'Projeto de Mecânica / Caldeiraria'],
  ['AMB', 'Ambiental'],
  ['COMP', 'Compatibilização'],
  ['ORC', 'Orçamento'],
  ['ENG', 'Engenharia'],
  ['JUR', 'Jurídico'],
  ['MULT', 'Multidisciplinar'],
  ['ECON', 'Economico fincanceiro'],
  ['GEOM', 'Geométrico'],
  ['GEO', 'Geofísicos'],
  ['HAB', 'Habitação'],
  ['VIAR', 'Viário'],
  ['MOBI', 'Mobilidade'],
  ['DES', 'Desapropriação'],
  ['CLSH', 'Clash'],
  ['SUP', 'Supervisão'],
  ['GER', 'Gerenciamento'],
  ['GECO', 'Gestão do Contrato'],
  ['CONF', 'Conformidade'],
] as const;
